# The name of the workflow, which will appear in the "Actions" tab on GitHub.
name: Deploy Canvas to GitHub Pages

# --- Triggers ---
on:
  push:
    branches:
      - main
    paths:
      - 'source/canvas.aseprite'
      - 'index.html'
      # Also trigger on changes to our conversion script
      - 'scripts/convert.js' 

  workflow_dispatch:

# --- Jobs ---
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # --- Steps ---
    steps:
      # Step 1: Check out the repository's code.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the Node.js environment.
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install the NEW, more reliable Aseprite parser library.
      # We are switching to 'aseprite-reader'.
      - name: Install Aseprite parser
        run: npm install aseprite-reader

      # Step 4: Run our custom conversion script.
      # The script itself will use this new library.
      - name: Convert Aseprite to JSON
        run: node scripts/convert.js

      # Step 5: Copy the main HTML file to the public directory.
      - name: Copy index.html into public directory
        run: cp index.html public/

      # Step 6: Deploy the contents of the 'public' directory to GitHub Pages.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
