name: Deploy Canvas to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'source/canvas.png'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install VIPS
        run: sudo apt-get update && sudo apt-get install -y libvips-tools

      - name: Generate DZI tiles
        run: vips dzsave source/canvas.png public --layout dz --suffix .jpeg[Q=90]

      - name: Copy index.html to public directory
        run: cp index.html public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
