# The name of the workflow, which will appear in the "Actions" tab on GitHub.
name: Deploy Canvas to GitHub Pages

# --- Triggers ---
# This section defines when the workflow should automatically run.
on:
  push:
    branches:
      - main
    paths:
      - 'source/canvas.aseprite'
      - 'index.html'
  
  # This allows you to manually trigger the workflow from the "Actions" tab.
  workflow_dispatch:

# --- Jobs ---
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # --- Steps ---
    steps:
      # Step 1: Check out the repository's code.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the Node.js environment.
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install the Aseprite to JSON converter tool.
      - name: Install Aseprite utility (ase-util)
        run: npm install -g ase-util

      # Step 4: Find the path where npm installed the tool.
      # 'npm bin -g' prints the directory for globally installed packages.
      # We store this path in an environment variable called 'NPM_BIN' for later use.
      - name: Get npm global bin path
        id: npm_bin
        run: echo "path=$(npm bin -g)" >> $GITHUB_OUTPUT

      # Step 5: Create a directory for the published site.
      - name: Create public directory
        run: mkdir public

      # Step 6: Convert the Aseprite file to JSON using the full path.
      # We now call the tool using the path we found in the previous step.
      # This ensures the system knows exactly where to find 'ase-util'.
      - name: Convert Aseprite to JSON
        run: ${{ steps.npm_bin.outputs.path }}/ase-util export --output-dir public --data-filename canvas.json source/canvas.aseprite

      # Step 7: Copy the main HTML file to the public directory.
      - name: Copy index.html into public directory
        run: cp index.html public/

      # Step 8: Deploy the contents of the 'public' directory to GitHub Pages.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
