name: Deploy Canvas to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'source/canvas.png'
      - 'index.html'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Новый блок: Выдаем роботу права на запись в репозиторий
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install VIPS
        run: sudo apt-get update && sudo apt-get install -y libvips-tools

      - name: Create public directory
        run: mkdir public

      - name: Generate DZI tiles into public directory
        run: vips dzsave source/canvas.png public/canvas --layout dz --suffix .jpeg[Q=90]

      - name: Copy index.html into public directory
        run: cp index.html public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
